(define (problem strips-sat-x-1)
 (:domain satellite)
 (:objects )
 (:init (pointing_satellite0_star2) (power_avail_satellite0))
 (:goal (and (pointing_satellite0_star5) (have_image_planet3_image0) (have_image_star5_thermograph2) (have_image_star6_thermograph2)))
 (:metric minimize (total-time))
)
